Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -40,6 +40,63 @@ commands:
               exit 1
             fi
 jobs:
+
+  run-migrations:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+    #  - run:
+    #      name: Install dependencies
+    #      command: |
+    #        sudo apt update
+    #        sudo apt upgrade -y
+    #        sudo apt install -y awscli
+      - run:
+          name: Run migrations
+          no_output_timeout: 30m
+          command: |
+            ls -la
+            pwd
+            cd ~/project/backend
+            pwd
+            npm i
+            npm run build
+            npm i pg
+            npm run migrations:revert
+            echo " pwd ---> " pwd
+            ls -la
+            ls .env
+            cat .env
+            touch migrations_dump.txt
+            ls
+            npm run migrations > ~/project/backend/migrations_dump.txt
+            cat migrations_dump.txt
+          # Your code here
+          # exit 1
+      - run:
+          name: Send migration results to memstash
+          command: |
+            cd ~/project/backend
+            cat ~/project/backend/migrations_dump.txt
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+              curl -H "Content-Type: text/plain" -H "token:${CIRCLE_WORKFLOW_ID:0:7}" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+              echo migration_${CIRCLE_WORKFLOW_ID}
+              echo "SUCCESS = 0"
+            else
+              echo $(curl -H "Content-Type: text/plain" -H "token:${CIRCLE_WORKFLOW_ID:0:7}" --request PUT --data "0" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7} | grep "No migrations happened")
+              echo "migration ID" migration_${CIRCLE_WORKFLOW_ID}
+              echo "FAIL = 1"
+            fi
+          # Your code here
+          # exit 1
+      - revert-migrations
+      - destroy-environment
+
+
   deploy-frontend:
     docker:
       - image: amazon/aws-cli
@@ -231,5 +288,12 @@ jobs:
 workflows:
   default:
     jobs:
-      - sm-test
+     - run-migrations
+      - deploy-frontend:
+          requires: [deploy-backend]
+      - deploy-backend:
+          requires: [run-migrations]
+      - sm-test:
+          requires: [deploy-backend, deploy-frontend]
+
     
